stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project CleaningOptimization.xcodeproj -scheme CleaningOptimization | xcpretty
    - xcodebuild test -project CleaningOptimization.xcodeproj -scheme CleaningOptimization -destination 'platform=iOS Simulator,name=iPad (7th generation),OS=13.3' | xcpretty -s
  tags:
    - ios_13-3
    - xcode_11-3
    - osx_10-15
