stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project TeamCleaningOptimisation.xcodeproj -scheme TeamCleaningOptimization 
    - xcodebuild test -project TeamCleaningOptimisation.xcodeproj -scheme TeamCleaningOptimization -destination 'platform=iOS Simulator,name=iPad Air (3rd generation),OS=13.3'
  tags:
    - ios_13-3
    - xcode_11-3
    - osx_10-13
    
